//
//  InteropVectorsTests.swift
//  ACE SDK
//
//  Cross-language interoperability tests using the canonical ACE test vectors
//  (`ace-spec/test-vectors.json`, generated by `spec/generate-vectors.py` from
//  the Python SDK). The same file is consumed by the TypeScript and Python SDKs.
//
//  Covers: ACE_KEM_SALT, identity derivation (X-Wing public key from the 32-byte
//  seed), conversationId, signData, signatures, the X-Wing draft-11 KEM vector,
//  and decryption of a Python-produced encrypted message.
//

import Testing
import Foundation
import CryptoKit
@testable import ACE

@Suite("Interop Vectors (V1)")
struct InteropVectorsTests {

    private struct Vectors: Decodable {
        let version: String
        let agents: [String: AgentVectors]
        let xwing: XWingVector
        let vectors: VectorData
    }

    private struct AgentVectors: Decodable {
        let scheme: String
        let signingPrivateKey: String
        let encryptionPrivateKey: String // Base64(32-byte X-Wing seed)
        let signingPublicKey: String
        let encryptionPublicKey: String // Base64(1216-byte X-Wing public key)
        let address: String
        let aceId: String
    }

    private struct XWingVector: Decodable {
        let seed: String // hex 32
        let publicKey: String // hex 1216
        let ciphertext: String // hex 1120
        let sharedSecret: String // hex 32
    }

    private struct VectorData: Decodable {
        let aceKemSalt: String
        let conversationId: String
        let signData: SignDataVector
        let signature: SignatureVector
        let encryptedMessage: EncryptedMessageVector
    }

    private struct SignDataVector: Decodable {
        let action: String
        let aceId: String
        let timestamp: Int
        let messagePayload: MessagePayloadVector
        let signDataHex: String
    }

    private struct MessagePayloadVector: Decodable {
        let type: String
        let to: String
        let conversationId: String
        let messageId: String
        let threadId: String
        let kemCiphertext: String
        let ciphertext: String
    }

    private struct SignatureVector: Decodable {
        let scheme: String
        let signDataHex: String
        let signatureValue: String
    }

    private struct EncryptedMessageVector: Decodable {
        let from: String
        let to: String
        let envelope: ACEMessage
        let expectedBody: [String: String]
    }

    private static let vectorsPath = Bundle.module.url(forResource: "test-vectors", withExtension: "json", subdirectory: "Fixtures")!

    private func loadVectors() throws -> Vectors {
        let data = try Data(contentsOf: Self.vectorsPath)
        return try JSONDecoder().decode(Vectors.self, from: data)
    }

    private func makeIdentity(_ agent: AgentVectors) throws -> SoftwareIdentity {
        let scheme: SigningScheme = agent.scheme == "ed25519" ? .ed25519 : .secp256k1
        let export = SoftwareIdentityExport(
            scheme: scheme,
            signingPrivateKey: agent.signingPrivateKey,
            encryptionPrivateKey: agent.encryptionPrivateKey
        )
        return try SoftwareIdentity.fromExport(export)
    }

    @Test("vector file is protocol version 1.0")
    func version() throws {
        let v = try loadVectors()
        #expect(v.version == "1.0")
    }

    @Test("ACE KEM salt matches cross-language vector")
    func aceKemSalt() throws {
        let v = try loadVectors()
        #expect(ACEHex.encode(ACEEncryption.aceKemSalt) == v.vectors.aceKemSalt)
        #expect(v.vectors.aceKemSalt == ACEHex.encode(Data(SHA256.hash(data: Data("ace.protocol.kem.v1".utf8)))))
    }

    @Test("Alice (ed25519) identity derivation")
    func aliceIdentity() throws {
        let v = try loadVectors()
        let a = v.agents["alice"]!
        let alice = try makeIdentity(a)

        #expect(try ACEBase64.decode(a.encryptionPrivateKey).count == 32)
        #expect(alice.getACEId() == a.aceId)
        #expect(alice.getAddress() == a.address)
        #expect(ACEBase64.encode(alice.getSigningPublicKey()) == a.signingPublicKey)
        #expect(alice.getEncryptionPublicKey().count == 1216)
        #expect(ACEBase64.encode(alice.getEncryptionPublicKey()) == a.encryptionPublicKey)
    }

    @Test("Bob (secp256k1) identity derivation")
    func bobIdentity() throws {
        let v = try loadVectors()
        let b = v.agents["bob"]!
        let bob = try makeIdentity(b)

        #expect(try ACEBase64.decode(b.encryptionPrivateKey).count == 32)
        #expect(bob.getACEId() == b.aceId)
        #expect(bob.getAddress() == b.address)
        #expect(ACEBase64.encode(bob.getSigningPublicKey()) == b.signingPublicKey)
        #expect(bob.getEncryptionPublicKey().count == 1216)
        #expect(ACEBase64.encode(bob.getEncryptionPublicKey()) == b.encryptionPublicKey)
    }

    @Test("conversationId matches cross-language vector")
    func conversationId() throws {
        let v = try loadVectors()
        let aliceEnc = try ACEBase64.decode(v.agents["alice"]!.encryptionPublicKey)
        let bobEnc = try ACEBase64.decode(v.agents["bob"]!.encryptionPublicKey)

        let convId = try ACEEncryption.computeConversationId(pubA: aliceEnc, pubB: bobEnc)
        #expect(convId == v.vectors.conversationId)

        // Symmetric
        let convIdReverse = try ACEEncryption.computeConversationId(pubA: bobEnc, pubB: aliceEnc)
        #expect(convIdReverse == v.vectors.conversationId)
    }

    @Test("signData matches cross-language vector")
    func signData() throws {
        let v = try loadVectors()
        let sd = v.vectors.signData
        let mp = sd.messagePayload

        let kemCiphertext = try ACEBase64.decode(mp.kemCiphertext)
        #expect(kemCiphertext.count == 1120)
        let ciphertext = try ACEBase64.decode(mp.ciphertext)
        let messagePayload = ACESigning.encodePayload([
            .string(mp.type), .string(mp.to), .string(mp.conversationId), .string(mp.messageId), .string(mp.threadId),
            .data(kemCiphertext), .data(ciphertext)
        ])
        let signData = ACESigning.buildSignData(
            action: sd.action,
            aceId: sd.aceId,
            timestamp: sd.timestamp,
            payload: messagePayload
        )
        #expect(ACEHex.encode(signData) == sd.signDataHex)
    }

    @Test("ed25519 signature verification against cross-language vector")
    func ed25519SignatureVerification() throws {
        let v = try loadVectors()
        let sigV = v.vectors.signature
        let alice = v.agents["alice"]!

        let signData = try ACEHex.decode(sigV.signDataHex)
        let sigBytes = try ACESigning.decodeSignature(sigV.signatureValue, scheme: .ed25519)
        let pubKey = try ACEBase64.decode(alice.signingPublicKey)

        let valid = ACESigning.verifySignature(
            signData: signData,
            signature: sigBytes,
            scheme: .ed25519,
            signingPublicKey: pubKey
        )
        #expect(valid)
    }

    @Test("Alice signs and Swift-produced signature verifies")
    func crossSignAndVerify() throws {
        // Note: Apple CryptoKit adds synthetic randomness to Ed25519 signatures
        // for fault injection protection, so we can't compare exact signature bytes.
        // Instead, verify that Swift-produced signatures are valid.
        let v = try loadVectors()
        let a = v.agents["alice"]!
        let alice = try makeIdentity(a)

        let signData = try ACEHex.decode(v.vectors.signData.signDataHex)
        let (sig, scheme) = try alice.sign(signData)
        #expect(scheme == .ed25519)

        let pubKey = try ACEBase64.decode(a.signingPublicKey)
        let valid = ACESigning.verifySignature(
            signData: signData,
            signature: sig,
            scheme: .ed25519,
            signingPublicKey: pubKey
        )
        #expect(valid)
    }

    @Test("X-Wing draft-11 vector: keygen(seed) → pk and decapsulate(ct) → ss")
    func xwingVector() throws {
        let v = try loadVectors()
        let seed = try ACEHex.decode(v.xwing.seed)
        let ct = try ACEHex.decode(v.xwing.ciphertext)
        #expect(seed.count == 32)
        #expect(ct.count == 1120)

        let pk = try ACEEncryption.publicKey(fromSeed: seed)
        #expect(pk.count == 1216)
        #expect(ACEHex.encode(pk) == v.xwing.publicKey)

        let sk = try XWingMLKEM768X25519.PrivateKey(seedRepresentation: seed, publicKey: nil)
        let ss = try sk.decapsulate(ct).withUnsafeBytes { Data($0) }
        #expect(ACEHex.encode(ss) == v.xwing.sharedSecret)
    }

    @Test("Python-encrypted message parses, verifies and decrypts as Bob")
    func decryptPythonMessage() throws {
        let v = try loadVectors()
        let em = v.vectors.encryptedMessage
        let aliceV = v.agents[em.from]!
        let bobV = v.agents[em.to]!
        let bob = try makeIdentity(bobV)
        let envelope = em.envelope

        #expect(envelope.ace == "1.0")
        #expect(envelope.from == aliceV.aceId)
        #expect(envelope.to == bobV.aceId)
        #expect(envelope.conversationId == v.vectors.conversationId)
        #expect(try ACEBase64.decode(envelope.encryption.kemCiphertext).count == 1120)

        // Vector timestamps are fixed; pin "now" to the envelope's timestamp.
        var opts = ParseMessageOptions(
            stateMachine: ThreadStateMachine(),
            expectedScheme: aliceV.scheme == "ed25519" ? .ed25519 : .secp256k1,
            replayDetector: ReplayDetector(),
            senderEncryptionPubKey: try ACEBase64.decode(aliceV.encryptionPublicKey)
        )
        opts.currentTimestamp = envelope.timestamp

        let parsed = try parseMessage(
            envelope,
            receiver: bob,
            senderSigningPubKey: try ACEBase64.decode(aliceV.signingPublicKey),
            opts: opts
        )

        #expect(parsed.from == aliceV.aceId)
        #expect(parsed.to == bobV.aceId)
        #expect(parsed.body.count == em.expectedBody.count)
        for (key, value) in em.expectedBody {
            #expect(parsed.body[key] as? String == value, "body[\(key)]")
        }
    }

    @Test("Python-encrypted message also decrypts via the raw ACEEncryption API")
    func decryptPythonMessageRaw() throws {
        let v = try loadVectors()
        let em = v.vectors.encryptedMessage
        let bobV = v.agents[em.to]!
        let seed = try ACEBase64.decode(bobV.encryptionPrivateKey)

        let plaintext = try ACEEncryption.decrypt(
            kemCiphertext: try ACEBase64.decode(em.envelope.encryption.kemCiphertext),
            payload: try ACEBase64.decode(em.envelope.encryption.payload),
            seed: seed,
            conversationId: em.envelope.conversationId
        )
        let body = try JSONSerialization.jsonObject(with: plaintext) as? [String: Any]
        #expect(body != nil)
        for (key, value) in em.expectedBody {
            #expect(body?[key] as? String == value, "body[\(key)]")
        }
    }
}
